Complete 3rd homework
lukamajstorovic/android-vjestina-tmdb pull request #3
Opened 2022-12-15 02:09 UTC by lukamajstorovic

2022-12-15 02:14 UTC, lukamajstorovic commented
When I navigate to the movie details screen, the app crashes. The error which pops up is:
java.lang.IllegalArgumentException: Key 1 was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
In MovieDetailsScreen, when I remove crew and cast composables from the MovieDetailsScreen function, the rest loads OK.

2023-01-02 14:08 UTC, fjandel-five requested changes

2023-01-02 14:08 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeViewModel.kt
> +                getPopular(homeScreenMapper)
You shouldn't call `getPopular()` method here. Instead, you should emit newly selected movie category to `popularSelectedCategory`, and this should cause updating `popularMoviesHomeViewState`. In order to achieve that, you need to define `popularSelectedCategory` as `MutableStateFlow`, and than use this flow together with `movieRepository.popularMovies(...)` flow in order to produce `popularMoviesHomeViewState` . You can achieve this with `flatMapLatest` and `stateIn` operators like this:

```kotlin
private val popularMoviesCategorySelected = MutableStateFlow(MovieCategory.POPULAR_STREAMING)

val popularCategoryViewState: StateFlow<HomeMovieCategoryViewState> =
    popularMoviesCategorySelected
        .flatMapLatest { selectedMovieCategory ->
            movieRepository.popularMovies(selectedMovieCategory)
                .map { popularMovies ->
                    homeScreenMapper.toHomeMovieCategoryViewState(
                        movieCategories = popularMovieCategories, // listOf(MovieCategory.POPULAR ...)
                        selectedMovieCategory = selectedMovieCategory,
                        movies = popularMovies,
                    )
                }
        }
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = homeScreenMapper.toHomeMovieCategoryViewState(
                movieCategories = popularMovieCategories, // listOf(MovieCategory.POPULAR ...)
                selectedMovieCategory = popularMoviesCategorySelected.value,
                movies = emptyList(),
            )
        )
```

With this approach, you won't need to have `getPopular(...)` and `initializeMovieCategories()` functions (as well as `getUpcoming` and `getNowPlaying`).

2023-01-02 14:08 UTC, fjandel-five commented on app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeViewModel.kt
> +                getPopular(homeScreenMapper)
You should define this behaviour for producing view states to all your view models (`HomeViewModel`, `FavoritesViewModel`, `MovieDetailsViewModel`).

2023-01-09 12:41 UTC, fjandel-five approved these changes

2023-01-09 18:36 UTC, merged